apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-auth-microservice
  labels:
    app: udagram-auth-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-auth-microservice
  template:
    metadata:
      labels:
        app: udagram-auth-microservice
    spec:
      containers:
        - name: udagram-auth-microservice
          image: thedemon12/udagram-auth-microservice
          ports:
            - containerPort: 80
