apiVersion: v1
kind: Service
metadata:
  name: udagram-auth-microservice
  labels:
    run: udagram-auth-microservice
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    run: udagram-auth-microservice
